server:
  port: 8000

spring:
  application:
    name: gulimall-member

  datasource:
    username: tifa
    password: rootPassword
    url: jdbc:mysql://10.200.200.1:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      server-addr: 10.200.200.1:8848
      config:
        import-check:
          enabled: false
