server:
  port: 9000

spring:
  application:
    name: gulimall-order

  datasource:
    username: tifa
    password: rootPassword
    url: jdbc:mysql://10.200.200.1:3306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 10.200.200.1:8848
      config:
        import-check:
          enabled: false

  rabbitmq:
    host: 10.200.200.1
    port: 5672
    virtual-host: /
    username: admin
    password: admin123

    #消费端需要手动确认
    listener:
      simple:
        acknowledge-mode: manual
    #        开启发送端确认
    publisher-confirm-type: correlated
    #    开启发送端消息抵达队列的确认
    publisher-returns: true
    #    开启发送端消息抵达队列的异步的确认
    template:
      mandatory: true

