server:
  port: 31000

spring:
  application:
    name: gulimall-search

  thymeleaf:
    cache: false

  data:
    redis:
      host: 10.200.200.1
      port: 6379
  cloud:
    nacos:
      server-addr: 10.200.200.1:8848
      config:
        import-check:
          enabled: false


