server:
  port: 9874

spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      server-addr: 10.200.200.1:8848
      config:
        import-check:
          enabled: false

  data:
    redis:
      host: 10.200.200.1
      port: 6379
